### ISSUE TITLE
Don't restart video when rotating phone

### ISSUE THREAD

**Issue by nagarrido** [savvasdalkitsis/uhuruphotos-android#554] opened 2024-01-25 11:33 UTC
Right now if I am watching a video, if I rotate my phone the video restarts. It would be nice to rotate the phone and keep playing the video from the same timestamp

**Comment by savvasdalkitsis** [comment] 2024-01-25 12:42
Duplicate of #98

**Closed by savvasdalkitsis** 2024-01-25 12:42 UTC
