### ISSUE TITLE
Shared photos view

### ISSUE THREAD

**Issue by nagarrido** [savvasdalkitsis/uhuruphotos-android#482] opened 2023-11-29 18:11 UTC
It would be nice to have a section for shared photos. This is, public, shared by me and shared with me

**Comment by savvasdalkitsis** [comment] 2024-01-24 19:33
Duplicate of https://github.com/savvasdalkitsis/uhuruphotos-android/issues/459

**Closed by savvasdalkitsis** 2024-01-24 19:33 UTC
