### ISSUE TITLE
Local media sync exception

### ISSUE THREAD

**Issue by sfaucheux** [savvasdalkitsis/uhuruphotos-android#481] opened 2023-11-22 03:02 UTC
First, thank you for this awesome app, it it works perfectly on some of my devices.

I am trying to use it on another device, but I cannot get the local media scan to work. When clicking "start", I can see the progress bar at 0% for a fraction of a second, and then it disappears.

Checking the logs I can see a warning related to the database:
```
2023-11-22 01:00:09,001 WARN  [<MediaStore> DatabaseUtils:179 readExceptionFromParcel]: android.database.sqlite.SQLiteException: no such column: orientation (code 1 SQLITE_ERROR[1]): , while compiling: SELECT _id, _display_name, width, height, _size, datetaken, _data, orientation, bucket_id, bucket_display_name FROM video WHERE (bucket_id = ?)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:179)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
	at android.content.ContentResolver.query(ContentResolver.java:809)
	at android.content.ContentResolver.query(ContentResolver.java:759)
	at androidx.core.content.ContentResolverCompat$Api16Impl.query(ContentResolverCompat.java:119)
	at androidx.core.content.ContentResolverCompat.query(ContentResolverCompat.java:87)
	at com.savvasdalkitsis.uhuruphotos.feature.media.local.domain.implementation.service.LocalMediaService.query(LocalMediaService.kt:195)
	at com.savvasdalkitsis.uhuruphotos.feature.media.local.domain.implementation.service.LocalMediaService.getVideosForBucket(LocalMediaService.kt:100)
	at com.savvasdalkitsis.uhuruphotos.feature.media.local.domain.implementation.repository.LocalMediaRepository.refresh(LocalMediaRepository.kt:87)
	at com.savvasdalkitsis.uhuruphotos.feature.media.local.domain.implementation.usecase.LocalMediaUseCase.refreshAll(LocalMediaUseCase.kt:266)
	at com.savvasdalkitsis.uhuruphotos.feature.media.local.domain.implementation.worker.LocalMediaSyncWorker.work(LocalMediaSyncWorker.kt:49)
	at com.savvasdalkitsis.uhuruphotos.feature.media.local.domain.implementation.worker.LocalMediaSyncWorker$work$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

Version: 0.0.157
Android version: 9

I tried reinstalling the app, clearing data and cache. Also tried not being logged into the librephotos server, same issue.
There are ~3000 local photos/videos on the device.

**Comment by savvasdalkitsis** [comment] 2024-01-25 19:04
Might be caused by #445

**Comment by savvasdalkitsis** [comment] 2024-02-25 14:02
I belive this is now fixed and will be releaseed in the next release

**Closed by savvasdalkitsis** 2024-02-25 14:02 UTC
Labels: bug
