### ISSUE TITLE
Photos endlessly uploading to server

### ISSUE THREAD

**Issue by nagarrido** [savvasdalkitsis/uhuruphotos-android#454] opened 2023-09-04 03:29 UTC
Everytime I enter the app, already backed up photos start the server sync process and the app tries to upload them again. I could provide logs if this is only happening to me and is not reproducible on your end.

**Comment by savvasdalkitsis** [comment] 2023-09-04 11:45
hm yea that shouldn't be happening if the photos are on the server. can you grab some logs and send them via the feedback button?

**Comment by redsunfex** [comment] 2024-01-18 09:42
Same thing happens here. On a secondary user (non-admin; 51,000 images; 80 items in upload folder) synchronizing images/videos (almost) always fails.

The media file is uploaded to the server but fails on synchronization, error log is filled with timeouts and interrupts. Media file is uploaded but does NOT end up scanned by librephotos instantly. Eventually it will appear on librephotos.

WARN  [RealCall:411 timeoutExit]: java.io.InterruptedIOException: timeout
WARN  [:null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

Only thing that fixes it is a full feed sync, then it gets the correct info from the server. 

Log included. This log generated from a crash -- some sort of memory leak caused by this issue.


[log.log](https://github.com/savvasdalkitsis/uhuruphotos-android/files/13974792/log.log)

**Comment by redsunfex** [comment] 2024-01-18 10:00
Here is the librephotos log for the above crash, looks like the server processed the file uhuru choked on correctly:

[ownphotos.log](https://github.com/savvasdalkitsis/uhuruphotos-android/files/13975011/ownphotos.log)

**Comment by savvasdalkitsis** [comment] 2024-01-24 19:25
I need to coordinate with @derneuere on how to best get mobile clients uploading media to the server. 

The issue here is that the app uploads the media, the server accepts it but the app cannot show the item as synchronised cause it is missing the information that the server will eventually process for the item after some time.

UhuruPhotos currently tries a few times to get the processed info from the server after each upload, with an exponential backoff between each attempt but that's not enough it seems.

The issue is more prominent on videos which take a long time to process on the backend.

I might have to rethink how the info syncing process works but it's a bit tricky as we run the risk of potentially checking for missing info from the server indefinitely.

Perhaps the api could return an 'accepted but not processed yet' response @derneuere? That would allow the app to offload the info sync process to really long running periods as long as the server indicates that files are still being processed?

**Comment by savvasdalkitsis** [comment] 2024-02-06 00:03
I believe this should be fixed in v0.0.165 using the latest release of LibrePhotos. Please reopen if that is not the case

**Closed by savvasdalkitsis** 2024-02-06 00:03 UTC
Labels: bug
