### ISSUE TITLE
Sync issue? on v0.0.157

### ISSUE THREAD

**Issue by vr6syncro** [savvasdalkitsis/uhuruphotos-android#479] opened 2023-10-29 20:24 UTC
Hey, it scanned all my files and it is showing them in the app but it has only synced one file to the server and now it is not sync anymore.
restarted the app did not help... 
any ideas? 

[log.log](https://github.com/savvasdalkitsis/uhuruphotos-android/files/13199153/log.log)

**Comment by vr6syncro** [comment] 2023-12-02 13:28
in the meantime i got a new handy. installed fresh but it is the same no sync from phone to the server

**Comment by savvasdalkitsis** [comment] 2024-01-24 19:31
Duplicate of #454

**Closed by savvasdalkitsis** 2024-01-24 19:31 UTC
